### ISSUE TITLE
Are measurements ignored?

### ISSUE THREAD

**Issue by aromanro** [pnnl/qasmtrans#5]
I'm investigating this project because I might use it in one of my projects.

The `qasm_parser` has a function, `loadin_circuit`, that translates the parsed qasm circuit into a `Circuit`.
It's quite simple, it just goes over the list of qasm 'gates' (dealing with them differently if they are conditional gates).

But... something is unclear to me: for a 'measure' instruction (simple, unconditional) the `generate_circuit` is called and that function simply ignores it: https://github.com/pnnl/qasmtrans/blob/e7d564547d42b2499577274604ab500cf18c451c/include/parser/qasm_parser.hpp#L512C5-L512C5

For a conditional instruction, it seems that the gates are added only if the `val` has the same value as the one specified for `if` https://github.com/pnnl/qasmtrans/blob/e7d564547d42b2499577274604ab500cf18c451c/include/parser/qasm_parser.hpp#L471, but that value I suppose should be available only during execution, after the measurement. `val` in this case seems to be simply 0, the initialization value.

Either I'm missing something or this looks like measurements are ignored. Is this by design?

Thank you for making this project available!

**Comment by huafei1137** [comment]
Hi Aromanro,

Thank you for your interests! To answer your questions:

1.The reason we ignore the measurment gate here is because we are generating the circuit, we do not need to gereate measure gate which does not exist in our transpiler and simulator. However, we have already stored the measurement qubit information in the creg_lsit and qreg_lsit. I remember when we generate the circuit, we will at the final add the measurement gate which is for measurement.

If you have any further question please let me know and I am happy to answer it!

**Comment by aromanro** [comment]
Thank you for the reply!
